id = "minimalistic dark theme"
name = "Minimalistic Dark"
description = "A minimalistic, pleasant dark theme with deep colors."
version = "0.1.0"
schema_version = 2
authors = ["j2cks"]
repository = "https://github.com/teenageswag/zed-theme"
